# Local Development Secrets Template
# Copy this file to .streamlit/secrets.toml and fill in your actual values
# For production deployment, use Streamlit Cloud secrets instead

GROQ_API_KEY = "your_groq_api_key_here"
EMAIL_ADDRESS = "your.email@gmail.com"
EMAIL_PASSWORD = "your_app_password_here"
SENDER_NAME = "Your Name"

# Note: For Streamlit Cloud deployment, add these secrets in the app settings
# The app automatically detects and uses Streamlit Cloud secrets when deployed 